### ISSUE TITLE
Support more technologies

### ISSUE THREAD

**Issue by Jinerhal** [Lioscro/ngs-tools#32]
Thanks for the great work! Could you please help add SeqScope and StarMap technology to `ngs.chemistry.get_chemistry`. And I'm wondering if seqFISH and MERFISH, which are not NGS, can be added too.

**Comment by Lioscro** [comment]
#35 

I couldn't find much info about the real resolution of starmap, seqfish and merfish probably because it depends on the microscope you use. LMK if this looks fine to you.
https://github.com/Lioscro/ngs-tools/pull/35/files#diff-17fe39651605989e7e296ac2fd1067568fb863d3914b7e2a9786084ec3f144d6R184-R199

**Comment by Jinerhal** [comment]
This looks great. Thanks a lot.
